name: Deploy Project

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEROKU_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
    - name: checkout repository code
      uses: actions/checkout@v1

    - name: install Java JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Build with Gradle
      run: ./gradlew build
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # https://devcenter.heroku.com/articles/authentication
    - name: create .netrc file for heroku authentication
      run: |+
          cat >~/.netrc <<EOF
          machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_KEY
          machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_KEY
          EOF

    - name: login to heroku cli
      run: heroku login

    - name: add heroku as git remote
      run: heroku git:remote -a $HEROKU_APP_NAME

    - name: deploy project to heroku
      run: git push heroku HEAD:refs/heads/main